export enum Colors {
    PRIMARY_ACCENT = "#9A6EC6",
    PRIMARY_ACCENT_BLUE_HUE = "#353d58",
    BLUE_DARKEST = "#0c1f31",
    PRIMARY_ACCENT_HUE = "#eceefa",
    PRIMARY_ACCENT_HUE_DARKER = "#edeff8",
    LAVENDER = "#9B99FF",
    WHITE = "#FFF",
    WHITE_OFF_WHITE = "#E9E9E9",
    BLACK = "#2C2C2C",
    TRANSPARENT = "#00000000",
    GREY_DARK = "#a5a5a5",
    GREY_DARKER = "#767676",
    GREY_LIGHT = "#EEEEEE",
    GREY = "#CCCCCC",
    RED = "#ba3446",
}
